#!/bin/bash


BASEDIR="$(pwd)/.."
INFO_DIR="info"
PDF_FILE="p2.pdf"
ZIPNAME="project.zip"
#force=false

#while getopts ":a:" opt; do
#  case $opt in
 #   a)
  #    #echo "-a was triggered, Parameter: $OPTARG" >&2
#		force=true
 #     ;;
 #   \?)
 #     echo "Invalid option: -$OPTARG" >&2
 #     exit 1
  #    ;;
#    :)
#      echo "Option -$OPTARG requires an argument." >&2
#      exit 1
#      ;;
 # esac
#done

cd $BASEDIR
make clean;make test
	echo -e "Do you still wish to continue? (Press Ctrl+c to exit or Enter to continue):"
	read
echo -e "\033[32mZipping....\e[0m"

cd $(mktemp -d)
cp -r $BASEDIR/src g08/

if ! [[ -f $BASEDIR/$INFO_DIR/$PDF_FILE ]];then
	echo -e "\033[31m[WARNING] No pdf file found. Zipping without slides!\e[0m Continue?"
	read
else
	cp  $BASEDIR/$INFO_DIR/$PDF_FILE g08
fi

zip -r $ZIPNAME g08 2>/dev/null
echo -e "\033[93mThe contents of the zip are:\n\e[0m $(unzip -l project.zip)\nContinue?"
read
mv $ZIPNAME $BASEDIR
echo "DONE!"
