(defmacro def-class (class &rest values)
	(let ((i 0))
	`(progn 
		(defun ,(intern(string-upcase (concatenate 'string  "make-" (string class) ))) (&key ,@values)
				(vector (string ,class) ,@values)
		)
			
		(defun ,(intern(string-upcase (concatenate 'string  (string class) "?" ))) (,class)
				(eql (string ,class) (aref ,class 0))
			)
			,@(mapcar 
				#'(lambda (x) 
					(incf i)
					`(defun ,(intern(string-upcase (concatenate 'string (string class) "-" (string x) ))) (,class)
						(aref ,class ,i)
					)
				) values)
		)
	)	
)
